// Generated by agent-handles from agent-handles/journey/v1 journeys. Do not edit;
// edit the journey manifest and recompile (npx agent-handles journeys compile).
import fs from "node:fs/promises";
import path from "node:path";
import { expect, test } from "@playwright/test";

const runtimeObserved = new Map<string, Set<string>>();
const pendingRuntimeReceipts = new Map<string, object>();
const runtimeRegistryPath = path.resolve(process.cwd(), "testid-registry.json");
type RuntimeRegistry = { entries?: Array<{ id: string }>; patterns?: Array<{ pattern: string }> };
let runtimeRegistryPromise: Promise<RuntimeRegistry> | undefined;

function loadRuntimeRegistry() {
  runtimeRegistryPromise ??= fs.readFile(runtimeRegistryPath, "utf8").then((text) => JSON.parse(text));
  return runtimeRegistryPromise;
}

function registryKnows(testId: string, registry: RuntimeRegistry) {
  if ((registry.entries ?? []).some((entry) => entry.id === testId)) return true;
  return (registry.patterns ?? []).some((entry) => entry.pattern.endsWith("*") && testId.startsWith(entry.pattern.slice(0, -1)));
}

test.afterAll(async () => {
  if (pendingRuntimeReceipts.size === 0) return;
  const directory = path.join(process.cwd(), ".agent-handles", "runtime-observations");
  await fs.mkdir(directory, { recursive: true });
  for (const [journeyName, receipt] of pendingRuntimeReceipts) {
    const file = journeyName.replace(/[^a-z0-9._-]+/gi, "-").replace(/^-+|-+$/g, "") || "journey";
    await fs.writeFile(path.join(directory, file + ".json"), JSON.stringify(receipt, null, 2) + "\n");
    runtimeObserved.delete(journeyName);
  }
  pendingRuntimeReceipts.clear();
});

async function captureRuntimeObservation(page: import("@playwright/test").Page) {
  let lastError: unknown;
  for (let attempt = 1; attempt <= 3; attempt += 1) {
    try {
      return await page.evaluate(async () => {
        await new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
        const RUNTIME_INTERACTIVE_SELECTOR =
          "button,input,select,textarea,a[href],summary,[contenteditable]:not([contenteditable='false']),[role='button'],[role='checkbox'],[role='combobox'],[role='link'],[role='menuitem'],[role='menuitemcheckbox'],[role='menuitemradio'],[role='option'],[role='radio'],[role='slider'],[role='spinbutton'],[role='switch'],[role='tab'],[role='textbox'],[role='treeitem'],[tabindex]:not([tabindex='-1'])";
        function isRuntimeObservationCandidate(element: Element) {
          if (element.closest("[data-agent-handles-overlay]")) return false;
          if (element.closest('[aria-hidden="true"]')) return false;
          const style = window.getComputedStyle(element);
          const rect = element.getBoundingClientRect();
          return style.display !== "none" && style.visibility !== "hidden" && rect.width > 0 && rect.height > 0;
        }
        const controls = Array.from(document.querySelectorAll(RUNTIME_INTERACTIVE_SELECTOR))
          .filter(isRuntimeObservationCandidate)
          .map((element) => ({
            testId: element.getAttribute("data-testid"),
            tag: element.tagName.toLowerCase(),
            role: element.getAttribute("role"),
            text: (element.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 120),
          }));
        const allIds = Array.from(document.querySelectorAll("[data-testid]"))
          .filter(isRuntimeObservationCandidate)
          .map((element) => element.getAttribute("data-testid"))
          .filter((value): value is string => Boolean(value));
        const duplicateTestIds = [...new Set(allIds.filter((value, index) => allIds.indexOf(value) !== index))].sort();
        return {
          url: location.href,
          controls,
          unidentified: controls.filter((control) => !control.testId),
          duplicateTestIds,
        };
      });
    } catch (error) {
      lastError = error;
      const navigationRace = /execution context was destroyed|most likely because of a navigation/iu.test(String(error));
      if (!navigationRace || attempt === 3) throw error;
      await page.waitForLoadState("domcontentloaded");
    }
  }
  throw lastError;
}

async function reconcileRuntime(page: import("@playwright/test").Page, journeyName: string, step: number) {
  const observation = await captureRuntimeObservation(page);
  const registry = await loadRuntimeRegistry();
  const unknownTestIds = observation.controls.filter((control) => control.testId && !registryKnows(control.testId, registry));
  const observed = runtimeObserved.get(journeyName) ?? new Set<string>();
  for (const control of observation.controls) if (control.testId) observed.add(control.testId);
  runtimeObserved.set(journeyName, observed);
  const receipt = {
    schema: "agent-handles/runtime-journey-observation/v1",
    measuredAt: new Date().toISOString(),
    journeyName,
    lastStep: step,
    pageUrl: observation.url,
    observedTestIds: [...observed].sort(),
    unidentified: observation.unidentified,
    unknownTestIds,
    duplicateTestIds: observation.duplicateTestIds,
    statement:
      [...observed].length +
      " controls observed during this journey; runtime evidence is path-bound, and unvisited states remain uncovered.",
  };
  pendingRuntimeReceipts.set(journeyName, receipt);
  expect(observation.unidentified, "visible interactive controls without data-testid after step " + step).toEqual([]);
  expect(unknownTestIds, "visible controls with identity values absent from the registry after step " + step).toEqual([]);
  expect(observation.duplicateTestIds, "duplicate visible data-testid values after step " + step).toEqual([]);
}

async function recordFinalPageState(page: import("@playwright/test").Page, journeyName: string) {
  const observation = await captureRuntimeObservation(page);
  const registry = await loadRuntimeRegistry();
  const unknownTestIds = observation.controls.filter((control) => control.testId && !registryKnows(control.testId, registry));
  const directory = path.join(process.cwd(), ".agent-handles", "visual-reviews");
  const file = journeyName.replace(/[^a-z0-9._-]+/gi, "-").replace(/^-+|-+$/g, "") || "journey";
  const screenshotPath = path.join(directory, "journey-" + file + ".png");
  await fs.mkdir(directory, { recursive: true });
  await page.screenshot({ path: screenshotPath, fullPage: true });
  const observedTestIds = [...new Set(observation.controls.map((control) => control.testId).filter(Boolean))].sort();
  const receipt = {
    schema: "agent-handles/page-state-review/v1",
    id: "journey-" + file,
    measuredAt: new Date().toISOString(),
    route: new URL(observation.url).pathname + new URL(observation.url).search,
    label: journeyName + " final state",
    title: await page.title(),
    evidenceKind: "compiled-journey-final",
    journeyName,
    visibleControls: observation.controls.length,
    identifiedControls: observation.controls.filter((control) => control.testId).length,
    issues: {
      unidentified: observation.unidentified.length,
      unknown: unknownTestIds.length,
      duplicate: observation.duplicateTestIds.length,
      reviewRequired: 0,
    },
    observedTestIds,
    screenshot: path.relative(process.cwd(), screenshotPath).replaceAll(path.sep, "/"),
    statement:
      observation.controls.length +
      " controls observed in the final state of " +
      journeyName +
      "; this is page/state evidence, and unvisited states remain uncovered.",
  };
  await fs.writeFile(path.join(directory, "journey-" + file + ".json"), JSON.stringify(receipt, null, 2) + "\n");
}

test("open-workspace-directly: The shareable workspace path loads a usable composer with no prior navigation.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await reconcileRuntime(page, "open-workspace-directly", 1);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "open-workspace-directly", 2);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeDisabled();
  await reconcileRuntime(page, "open-workspace-directly", 3);
  await recordFinalPageState(page, "open-workspace-directly");
});

test("start-a-new-conversation: The sidebar control creates a thread and the composer is ready with the send control idle.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.editorial-sidebar.begin-a-new-conversation").click();
  await reconcileRuntime(page, "start-a-new-conversation", 1);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "start-a-new-conversation", 2);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeDisabled();
  await reconcileRuntime(page, "start-a-new-conversation", 3);
  await recordFinalPageState(page, "start-a-new-conversation");
});

test("send-message-and-read-streamed-reply: Type a prompt, send it, and watch the mocked OpenRouter stream land in the transcript.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").fill("Summarize the tour harness in one line.");
  await reconcileRuntime(page, "send-message-and-read-streamed-reply", 1);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "send-message-and-read-streamed-reply", 2);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "send-message-and-read-streamed-reply", 3);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("The mocked OpenRouter stream answered this turn", { timeout: 20000 });
  await reconcileRuntime(page, "send-message-and-read-streamed-reply", 4);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "send-message-and-read-streamed-reply", 5);
  await recordFinalPageState(page, "send-message-and-read-streamed-reply");
});

test("stop-a-slow-streamed-reply: With a slow stream, the send control turns into stop; pressing it ends the turn and the composer goes idle.", async ({
  page,
}) => {
  await page.goto("/?scenario=slow-stream#/workspace");
  await page.getByTestId("workspace.composer.draft").fill("Tell me slowly.");
  await reconcileRuntime(page, "stop-a-slow-streamed-reply", 1);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "stop-a-slow-streamed-reply", 2);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "stop-a-slow-streamed-reply", 3);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("This reply arrives slowly", { timeout: 20000 });
  await reconcileRuntime(page, "stop-a-slow-streamed-reply", 4);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "stop-a-slow-streamed-reply", 5);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "stop-a-slow-streamed-reply", 6);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeDisabled();
  await reconcileRuntime(page, "stop-a-slow-streamed-reply", 7);
  await recordFinalPageState(page, "stop-a-slow-streamed-reply");
});

test("tool-turn-shows-activity-and-answer: The first reply is a tool call; its activity row expands and the follow-up answer reads the result back.", async ({
  page,
}) => {
  await page.goto("/?scenario=tool-turn#/workspace");
  await page.getByTestId("workspace.composer.draft").fill("What time is it?");
  await reconcileRuntime(page, "tool-turn-shows-activity-and-answer", 1);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "tool-turn-shows-activity-and-answer", 2);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "tool-turn-shows-activity-and-answer", 3);
  await expect(page.getByTestId("workspace.activity-row.toggle-call_time_1:0")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "tool-turn-shows-activity-and-answer", 4);
  await page.getByTestId("workspace.activity-row.toggle-call_time_1:0").click();
  await reconcileRuntime(page, "tool-turn-shows-activity-and-answer", 5);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("I checked the clock", { timeout: 20000 });
  await reconcileRuntime(page, "tool-turn-shows-activity-and-answer", 6);
  await recordFinalPageState(page, "tool-turn-shows-activity-and-answer");
});

test("web-search-grounded-reply: The assistant calls web_search, Brave answers with mocked sources, and the follow-up cites them.", async ({
  page,
}) => {
  await page.goto("/?scenario=web-search#/workspace");
  await page.getByTestId("workspace.composer.draft").fill("What is a journey catalog?");
  await reconcileRuntime(page, "web-search-grounded-reply", 1);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "web-search-grounded-reply", 2);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "web-search-grounded-reply", 3);
  await expect(page.getByTestId("workspace.activity-row.toggle-call_search_1:0")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "web-search-grounded-reply", 4);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("Two sources answered", { timeout: 20000 });
  await reconcileRuntime(page, "web-search-grounded-reply", 5);
  await recordFinalPageState(page, "web-search-grounded-reply");
});

test("image-generation-job-card: The assistant calls image_generate, the job runs against the mocked OpenRouter image endpoint, and the card renders the result.", async ({
  page,
}) => {
  await page.goto("/?scenario=image-job#/workspace");
  await page.getByTestId("workspace.composer.draft").fill("Draw a wax seal with the letter G.");
  await reconcileRuntime(page, "image-generation-job-card", 1);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "image-generation-job-card", 2);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "image-generation-job-card", 3);
  await expect(page.getByTestId("workspace.activity-row.toggle-call_image_1:0")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "image-generation-job-card", 4);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("The render is queued", { timeout: 20000 });
  await reconcileRuntime(page, "image-generation-job-card", 5);
  await expect(page.getByTestId("workspace.image-job-card.image")).toBeVisible({ timeout: 20000 });
  await reconcileRuntime(page, "image-generation-job-card", 6);
  await recordFinalPageState(page, "image-generation-job-card");
});

test("local-ollama-reply: With no cloud key and Ollama online, a turn is answered by the mocked local model.", async ({ page }) => {
  await page.goto("/?scenario=local-ollama#/workspace");
  await page.getByTestId("workspace.composer.draft").fill("Answer locally.");
  await reconcileRuntime(page, "local-ollama-reply", 1);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "local-ollama-reply", 2);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "local-ollama-reply", 3);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("Mock local reply from Ollama", { timeout: 20000 });
  await reconcileRuntime(page, "local-ollama-reply", 4);
  await recordFinalPageState(page, "local-ollama-reply");
});

test("provider-error-dismiss: OpenRouter fails with HTTP 500; the error surfaces in the transcript and the composer error can be dismissed.", async ({
  page,
}) => {
  await page.goto("/?scenario=provider-error#/workspace");
  await page.getByTestId("workspace.composer.draft").fill("This will fail.");
  await reconcileRuntime(page, "provider-error-dismiss", 1);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "provider-error-dismiss", 2);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "provider-error-dismiss", 3);
  await expect(page.getByTestId("workspace.editorial-composer.dismiss-chat-error")).toBeVisible({ timeout: 30000 });
  await reconcileRuntime(page, "provider-error-dismiss", 4);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("500", { timeout: 30000 });
  await reconcileRuntime(page, "provider-error-dismiss", 5);
  await page.getByTestId("workspace.editorial-composer.dismiss-chat-error").click();
  await reconcileRuntime(page, "provider-error-dismiss", 6);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "provider-error-dismiss", 7);
  await recordFinalPageState(page, "provider-error-dismiss");
});

test("bridge-offline-degrades-gracefully: With the bridge and Ollama unreachable, attachments are disabled but a cloud turn still completes.", async ({
  page,
}) => {
  await page.goto("/?scenario=bridge-offline#/workspace");
  await expect(page.getByTestId("workspace.composer.attach")).toBeDisabled();
  await reconcileRuntime(page, "bridge-offline-degrades-gracefully", 1);
  await page.getByTestId("workspace.composer.draft").fill("Still online?");
  await reconcileRuntime(page, "bridge-offline-degrades-gracefully", 2);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "bridge-offline-degrades-gracefully", 3);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "bridge-offline-degrades-gracefully", 4);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("The mocked OpenRouter stream answered this turn", { timeout: 20000 });
  await reconcileRuntime(page, "bridge-offline-degrades-gracefully", 5);
  await recordFinalPageState(page, "bridge-offline-degrades-gracefully");
});

test("rename-thread-from-context-menu: Right-click a thread, choose Rename, type a new title, and confirm it in the sidebar.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.editorial-sidebar.thread-agent-task").click({ button: "right" });
  await reconcileRuntime(page, "rename-thread-from-context-menu", 1);
  await page.getByTestId("workspace.editorial-sidebar.context-rename-agent-task").click();
  await reconcileRuntime(page, "rename-thread-from-context-menu", 2);
  await page.getByTestId("workspace.editorial-sidebar.rename-input-agent-task").fill("Renamed by the journey");
  await reconcileRuntime(page, "rename-thread-from-context-menu", 3);
  await page.getByTestId("workspace.editorial-sidebar.rename-input-agent-task").press("Enter");
  await reconcileRuntime(page, "rename-thread-from-context-menu", 4);
  await expect(page.getByTestId("workspace.editorial-sidebar.thread-agent-task")).toContainText("Renamed by the journey");
  await reconcileRuntime(page, "rename-thread-from-context-menu", 5);
  await recordFinalPageState(page, "rename-thread-from-context-menu");
});

test("pin-thread-from-row-actions: Hover a thread row and pin it; the row stays present.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.editorial-sidebar.thread-agent-task").hover();
  await reconcileRuntime(page, "pin-thread-from-row-actions", 1);
  await page.getByTestId("workspace.editorial-sidebar.pin-agent-task").click();
  await reconcileRuntime(page, "pin-thread-from-row-actions", 2);
  await expect(page.getByTestId("workspace.editorial-sidebar.thread-agent-task")).toBeVisible();
  await reconcileRuntime(page, "pin-thread-from-row-actions", 3);
  await recordFinalPageState(page, "pin-thread-from-row-actions");
});

test("delete-thread-and-undo: Deleting a thread shows an undo toast; undo restores the thread.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.editorial-sidebar.thread-agent-task").hover();
  await reconcileRuntime(page, "delete-thread-and-undo", 1);
  await page.getByTestId("workspace.editorial-sidebar.delete-agent-task").click();
  await reconcileRuntime(page, "delete-thread-and-undo", 2);
  await expect(page.getByTestId("workspace.undo-toast.undo")).toBeVisible();
  await reconcileRuntime(page, "delete-thread-and-undo", 3);
  await page.getByTestId("workspace.undo-toast.undo").click();
  await reconcileRuntime(page, "delete-thread-and-undo", 4);
  await expect(page.getByTestId("workspace.editorial-sidebar.thread-agent-task")).toBeVisible();
  await reconcileRuntime(page, "delete-thread-and-undo", 5);
  await recordFinalPageState(page, "delete-thread-and-undo");
});

test("switch-between-threads: Open the tool-activity thread, then return to the active one; each transcript renders its own content.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.editorial-sidebar.thread-tool").click();
  await reconcileRuntime(page, "switch-between-threads", 1);
  await expect(page.getByTestId("workspace.activity-row.toggle-tool-assistant:work-note:0")).toBeVisible();
  await reconcileRuntime(page, "switch-between-threads", 2);
  await page.getByTestId("workspace.editorial-sidebar.thread-active").click();
  await reconcileRuntime(page, "switch-between-threads", 3);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("Here is a short implementation note");
  await reconcileRuntime(page, "switch-between-threads", 4);
  await recordFinalPageState(page, "switch-between-threads");
});

test("edit-message-and-resend: Edit the user message, confirm the truncation, and a fresh reply streams in.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.editorial-message.message-active-user").hover();
  await reconcileRuntime(page, "edit-message-and-resend", 1);
  await page.getByTestId("workspace.editorial-message.edit-active-user").click();
  await reconcileRuntime(page, "edit-message-and-resend", 2);
  await page.getByTestId("workspace.editorial-message.edit-input-active-user").fill("Edited prompt from the journey");
  await reconcileRuntime(page, "edit-message-and-resend", 3);
  await page.getByTestId("workspace.editorial-message.edit-save-active-user").click();
  await reconcileRuntime(page, "edit-message-and-resend", 4);
  await expect(page.getByTestId("workspace.editorial-message.edit-confirm-save-active-user")).toBeVisible();
  await reconcileRuntime(page, "edit-message-and-resend", 5);
  await page.getByTestId("workspace.editorial-message.edit-confirm-save-active-user").click();
  await reconcileRuntime(page, "edit-message-and-resend", 6);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("The mocked OpenRouter stream answered this turn", { timeout: 20000 });
  await reconcileRuntime(page, "edit-message-and-resend", 7);
  await recordFinalPageState(page, "edit-message-and-resend");
});

test("regenerate-assistant-reply: Ask for a new answer to the same prompt and read the regenerated stream.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.editorial-message.message-active-assistant").hover();
  await reconcileRuntime(page, "regenerate-assistant-reply", 1);
  await page.getByTestId("workspace.editorial-message.regenerate-active-assistant").click();
  await reconcileRuntime(page, "regenerate-assistant-reply", 2);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("The mocked OpenRouter stream answered this turn", { timeout: 20000 });
  await reconcileRuntime(page, "regenerate-assistant-reply", 3);
  await recordFinalPageState(page, "regenerate-assistant-reply");
});

test("branch-conversation-from-message: Branching from the user message opens a new thread carrying that message.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.editorial-message.message-active-user").hover();
  await reconcileRuntime(page, "branch-conversation-from-message", 1);
  await page.getByTestId("workspace.editorial-message.branch-active-user").click();
  await reconcileRuntime(page, "branch-conversation-from-message", 2);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("screenshot tour", { timeout: 10000 });
  await reconcileRuntime(page, "branch-conversation-from-message", 3);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "branch-conversation-from-message", 4);
  await recordFinalPageState(page, "branch-conversation-from-message");
});

test("inspect-memory-disclosure: Open a memory chip to see why it was used and where it lives.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("Here is a short implementation note");
  await reconcileRuntime(page, "inspect-memory-disclosure", 1);
  await page.getByTestId("workspace.memory-disclosure.chip-note:audit-plan").hover();
  await reconcileRuntime(page, "inspect-memory-disclosure", 2);
  await page.getByTestId("workspace.memory-disclosure.chip-note:audit-plan").click();
  await reconcileRuntime(page, "inspect-memory-disclosure", 3);
  await expect(page.getByTestId("workspace.memory-disclosure.why-was-this-used")).toBeVisible();
  await reconcileRuntime(page, "inspect-memory-disclosure", 4);
  await expect(page.getByTestId("workspace.memory-disclosure.open-in-memory")).toBeVisible();
  await reconcileRuntime(page, "inspect-memory-disclosure", 5);
  await recordFinalPageState(page, "inspect-memory-disclosure");
});

test("exclude-memory-source-and-undo: Mark a memory source as not to be used, confirm, and reverse the choice from the undo control.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("Here is a short implementation note");
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 1);
  await page.getByTestId("workspace.memory-disclosure.chip-note:audit-plan").hover();
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 2);
  await page.getByTestId("workspace.memory-disclosure.chip-note:audit-plan").click();
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 3);
  await page.getByTestId("workspace.memory-disclosure.don-apos-t-use-this-source").click();
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 4);
  await expect(page.getByTestId("workspace.memory-disclosure.exclude")).toBeVisible();
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 5);
  await page.getByTestId("workspace.memory-disclosure.exclude").click();
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 6);
  await expect(page.getByTestId("workspace.memory-disclosure.undo-exclusion")).toBeVisible();
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 7);
  await page.getByTestId("workspace.memory-disclosure.undo-exclusion").click();
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 8);
  await expect(page.getByTestId("workspace.memory-disclosure.chip-note:audit-plan")).toBeVisible();
  await reconcileRuntime(page, "exclude-memory-source-and-undo", 9);
  await recordFinalPageState(page, "exclude-memory-source-and-undo");
});

test("search-models-in-popover: Open the model popover, filter by name, then clear the filter.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer-meta.model").click();
  await reconcileRuntime(page, "search-models-in-popover", 1);
  await expect(page.getByTestId("workspace.model-popover.search-models")).toBeVisible();
  await reconcileRuntime(page, "search-models-in-popover", 2);
  await page.getByTestId("workspace.model-popover.search-models").fill("gemini");
  await reconcileRuntime(page, "search-models-in-popover", 3);
  await expect(page.getByTestId("workspace.model-popover.row-auto-gemini-3-flash")).toBeVisible();
  await reconcileRuntime(page, "search-models-in-popover", 4);
  await page.getByTestId("workspace.model-popover.clear-model-search").click();
  await reconcileRuntime(page, "search-models-in-popover", 5);
  await expect(page.getByTestId("workspace.model-popover.search-models")).toBeVisible();
  await reconcileRuntime(page, "search-models-in-popover", 6);
  await recordFinalPageState(page, "search-models-in-popover");
});

test("choose-a-local-model: Switch the picker to local models and select the Ollama model for this thread.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer-meta.model").click();
  await reconcileRuntime(page, "choose-a-local-model", 1);
  await page.getByTestId("workspace.model-popover.segment-local").click();
  await reconcileRuntime(page, "choose-a-local-model", 2);
  await expect(page.getByTestId("workspace.model-popover.row-ollama-qwen2.5:7b")).toBeVisible();
  await reconcileRuntime(page, "choose-a-local-model", 3);
  await page.getByTestId("workspace.model-popover.row-ollama-qwen2.5:7b").click();
  await reconcileRuntime(page, "choose-a-local-model", 4);
  await expect(page.getByTestId("workspace.composer-meta.model")).toContainText("qwen2.5:7b");
  await reconcileRuntime(page, "choose-a-local-model", 5);
  await recordFinalPageState(page, "choose-a-local-model");
});

test("filter-models-by-capability: Toggle a capability filter in the model picker and keep the popover open.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer-meta.model").click();
  await reconcileRuntime(page, "filter-models-by-capability", 1);
  await page.getByTestId("workspace.model-popover.cap-filter-tools").click();
  await reconcileRuntime(page, "filter-models-by-capability", 2);
  await expect(page.getByTestId("workspace.model-popover.model-popover")).toBeVisible();
  await reconcileRuntime(page, "filter-models-by-capability", 3);
  await page.getByTestId("workspace.model-popover.cap-filter-tools").click();
  await reconcileRuntime(page, "filter-models-by-capability", 4);
  await expect(page.getByTestId("workspace.model-popover.model-popover")).toBeVisible();
  await reconcileRuntime(page, "filter-models-by-capability", 5);
  await recordFinalPageState(page, "filter-models-by-capability");
});

test("set-thinking-effort: Change the reasoning effort selector in the composer meta bar.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer-meta.thinking-effort").selectOption("high");
  await reconcileRuntime(page, "set-thinking-effort", 1);
  await expect(page.getByTestId("workspace.composer-meta.thinking-effort")).toBeVisible();
  await reconcileRuntime(page, "set-thinking-effort", 2);
  await recordFinalPageState(page, "set-thinking-effort");
});

test("command-palette-find-thread: Open the palette with the keyboard, search for a thread, and open it.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").click();
  await reconcileRuntime(page, "command-palette-find-thread", 1);
  await page.getByTestId("workspace.composer.draft").press("Control+k");
  await reconcileRuntime(page, "command-palette-find-thread", 2);
  await expect(page.getByTestId("app.command-palette.search-commands-and-threads")).toBeVisible();
  await reconcileRuntime(page, "command-palette-find-thread", 3);
  await page.getByTestId("app.command-palette.search-commands-and-threads").fill("Usage");
  await reconcileRuntime(page, "command-palette-find-thread", 4);
  await expect(page.getByTestId("app.command-palette.row-thread:usage")).toBeVisible();
  await reconcileRuntime(page, "command-palette-find-thread", 5);
  await page.getByTestId("app.command-palette.row-thread:usage").click();
  await reconcileRuntime(page, "command-palette-find-thread", 6);
  await expect(page.getByTestId("workspace.editorial-sidebar.thread-usage")).toBeVisible();
  await reconcileRuntime(page, "command-palette-find-thread", 7);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "command-palette-find-thread", 8);
  await recordFinalPageState(page, "command-palette-find-thread");
});

test("command-palette-new-conversation: The palette action creates a thread and leaves the composer idle.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").click();
  await reconcileRuntime(page, "command-palette-new-conversation", 1);
  await page.getByTestId("workspace.composer.draft").press("Control+k");
  await reconcileRuntime(page, "command-palette-new-conversation", 2);
  await expect(page.getByTestId("app.command-palette.search-commands-and-threads")).toBeVisible();
  await reconcileRuntime(page, "command-palette-new-conversation", 3);
  await page.getByTestId("app.command-palette.row-action:new-conversation").click();
  await reconcileRuntime(page, "command-palette-new-conversation", 4);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "command-palette-new-conversation", 5);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeDisabled();
  await reconcileRuntime(page, "command-palette-new-conversation", 6);
  await recordFinalPageState(page, "command-palette-new-conversation");
});

test("command-palette-open-settings: The palette action opens the settings menu.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").click();
  await reconcileRuntime(page, "command-palette-open-settings", 1);
  await page.getByTestId("workspace.composer.draft").press("Control+k");
  await reconcileRuntime(page, "command-palette-open-settings", 2);
  await expect(page.getByTestId("app.command-palette.search-commands-and-threads")).toBeVisible();
  await reconcileRuntime(page, "command-palette-open-settings", 3);
  await page.getByTestId("app.command-palette.row-action:settings").click();
  await reconcileRuntime(page, "command-palette-open-settings", 4);
  await expect(page.getByTestId("settings.gates-menu.tab-settings")).toBeVisible();
  await reconcileRuntime(page, "command-palette-open-settings", 5);
  await recordFinalPageState(page, "command-palette-open-settings");
});

test("browse-workspace-files-in-dock: Open the file explorer from the palette, enter a folder, and go back up.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").click();
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 1);
  await page.getByTestId("workspace.composer.draft").press("Control+k");
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 2);
  await expect(page.getByTestId("app.command-palette.search-commands-and-threads")).toBeVisible();
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 3);
  await page.getByTestId("app.command-palette.row-action:browse-files-in-dock").click();
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 4);
  await expect(page.getByTestId("workspace.dock.file-explorer")).toBeVisible();
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 5);
  await page.getByTestId("workspace.file-explorer-panel.entry-notes").click();
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 6);
  await expect(page.getByTestId("workspace.file-explorer-panel.parent-directory")).toBeEnabled();
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 7);
  await page.getByTestId("workspace.file-explorer-panel.parent-directory").click();
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 8);
  await expect(page.getByTestId("workspace.file-explorer-panel.entry-notes")).toBeVisible();
  await reconcileRuntime(page, "browse-workspace-files-in-dock", 9);
  await recordFinalPageState(page, "browse-workspace-files-in-dock");
});

test("open-task-center-and-close-it: The task center lists the seeded image job; closing its cell returns to the plain workspace.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").click();
  await reconcileRuntime(page, "open-task-center-and-close-it", 1);
  await page.getByTestId("workspace.composer.draft").press("Control+k");
  await reconcileRuntime(page, "open-task-center-and-close-it", 2);
  await expect(page.getByTestId("app.command-palette.search-commands-and-threads")).toBeVisible();
  await reconcileRuntime(page, "open-task-center-and-close-it", 3);
  await page.getByTestId("app.command-palette.row-action:open-task-center").click();
  await reconcileRuntime(page, "open-task-center-and-close-it", 4);
  await expect(page.getByTestId("workspace.task-center.ledger")).toBeVisible();
  await reconcileRuntime(page, "open-task-center-and-close-it", 5);
  await expect(page.getByTestId("workspace.task-center-panel.task-img-tour")).toBeVisible();
  await reconcileRuntime(page, "open-task-center-and-close-it", 6);
  await page.getByTestId("workspace.dock-panel.close-0").click();
  await reconcileRuntime(page, "open-task-center-and-close-it", 7);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "open-task-center-and-close-it", 8);
  await recordFinalPageState(page, "open-task-center-and-close-it");
});

test("collapse-a-dock-cell: Open the explorer in the dock, collapse it to the rail, and expand it again.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").click();
  await reconcileRuntime(page, "collapse-a-dock-cell", 1);
  await page.getByTestId("workspace.composer.draft").press("Control+k");
  await reconcileRuntime(page, "collapse-a-dock-cell", 2);
  await expect(page.getByTestId("app.command-palette.search-commands-and-threads")).toBeVisible();
  await reconcileRuntime(page, "collapse-a-dock-cell", 3);
  await page.getByTestId("app.command-palette.row-action:browse-files-in-dock").click();
  await reconcileRuntime(page, "collapse-a-dock-cell", 4);
  await expect(page.getByTestId("workspace.dock.file-explorer")).toBeVisible();
  await reconcileRuntime(page, "collapse-a-dock-cell", 5);
  await page.getByTestId("workspace.dock-panel.collapse-0").click();
  await reconcileRuntime(page, "collapse-a-dock-cell", 6);
  await expect(page.getByTestId("workspace.dock.collapsed-rail")).toBeVisible();
  await reconcileRuntime(page, "collapse-a-dock-cell", 7);
  await page.getByTestId("workspace.dock-panel.expand-dock").click();
  await reconcileRuntime(page, "collapse-a-dock-cell", 8);
  await expect(page.getByTestId("workspace.dock.panel")).toBeVisible();
  await reconcileRuntime(page, "collapse-a-dock-cell", 9);
  await recordFinalPageState(page, "collapse-a-dock-cell");
});

test("open-settings-and-switch-theme: Reach Settings through the sidebar control and select the Light theme.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "open-settings-and-switch-theme", 1);
  await expect(page.getByTestId("settings.gates-menu.tab-settings")).toBeVisible();
  await reconcileRuntime(page, "open-settings-and-switch-theme", 2);
  await page.getByTestId("settings.segmented.option-theme-light").click();
  await reconcileRuntime(page, "open-settings-and-switch-theme", 3);
  await expect(page.getByTestId("settings.preferences.export-json")).toBeVisible();
  await reconcileRuntime(page, "open-settings-and-switch-theme", 4);
  await recordFinalPageState(page, "open-settings-and-switch-theme");
});

test("theme-persists-across-reload: Pick the light theme, reload with storage kept straight into the settings route, and find the theme control still there.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await reconcileRuntime(page, "theme-persists-across-reload", 1);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "theme-persists-across-reload", 2);
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "theme-persists-across-reload", 3);
  await page.getByTestId("settings.segmented.option-theme-light").click();
  await reconcileRuntime(page, "theme-persists-across-reload", 4);
  await page.goto("/?scenario=desktop-ready&persist=1#/menu/settings");
  await reconcileRuntime(page, "theme-persists-across-reload", 5);
  await expect(page.getByTestId("settings.gates-menu.tab-settings")).toBeVisible();
  await reconcileRuntime(page, "theme-persists-across-reload", 6);
  await expect(page.getByTestId("settings.segmented.option-theme-light")).toBeVisible();
  await reconcileRuntime(page, "theme-persists-across-reload", 7);
  await recordFinalPageState(page, "theme-persists-across-reload");
});

test("light-theme-preselected: The light-theme scenario opens with Light already selected in settings.", async ({ page }) => {
  await page.goto("/?scenario=light-theme#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "light-theme-preselected", 1);
  await expect(page.getByTestId("settings.segmented.option-theme-light")).toBeVisible();
  await reconcileRuntime(page, "light-theme-preselected", 2);
  await expect(page.getByTestId("settings.segmented.option-theme-dark")).toBeVisible();
  await reconcileRuntime(page, "light-theme-preselected", 3);
  await recordFinalPageState(page, "light-theme-preselected");
});

test("open-model-provider-settings: Open the menu, select Models, and verify the web-search provider card renders.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "open-model-provider-settings", 1);
  await expect(page.getByTestId("settings.gates-menu.tab-models")).toBeVisible();
  await reconcileRuntime(page, "open-model-provider-settings", 2);
  await page.getByTestId("settings.gates-menu.tab-models").click();
  await reconcileRuntime(page, "open-model-provider-settings", 3);
  await expect(page.getByTestId("settings.models.search-card")).toContainText("Web search");
  await reconcileRuntime(page, "open-model-provider-settings", 4);
  await recordFinalPageState(page, "open-model-provider-settings");
});

test("replace-openrouter-key: Remove the stored key, enter a placeholder, connect, and see it stored again.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "replace-openrouter-key", 1);
  await page.getByTestId("settings.gates-menu.tab-models").click();
  await reconcileRuntime(page, "replace-openrouter-key", 2);
  await expect(page.getByTestId("settings.secret-key.stored-openrouter")).toBeVisible();
  await reconcileRuntime(page, "replace-openrouter-key", 3);
  await page.getByTestId("settings.secret-key.remove-openrouter").click();
  await reconcileRuntime(page, "replace-openrouter-key", 4);
  await expect(page.getByTestId("settings.secret-key.input-openrouter")).toBeVisible();
  await reconcileRuntime(page, "replace-openrouter-key", 5);
  await page.getByTestId("settings.secret-key.input-openrouter").fill("journey-placeholder-not-a-real-key");
  await reconcileRuntime(page, "replace-openrouter-key", 6);
  await page.getByTestId("settings.secret-key.connect-openrouter").click();
  await reconcileRuntime(page, "replace-openrouter-key", 7);
  await expect(page.getByTestId("settings.secret-key.stored-openrouter")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "replace-openrouter-key", 8);
  await recordFinalPageState(page, "replace-openrouter-key");
});

test("set-ollama-endpoint: Enter the local Ollama URL under Models and commit it.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "set-ollama-endpoint", 1);
  await page.getByTestId("settings.gates-menu.tab-models").click();
  await reconcileRuntime(page, "set-ollama-endpoint", 2);
  await page.getByTestId("settings.models-api-section.http-127-0-0-1-11434").fill("http://127.0.0.1:11434");
  await reconcileRuntime(page, "set-ollama-endpoint", 3);
  await page.getByTestId("settings.models-api-section.commit").click();
  await reconcileRuntime(page, "set-ollama-endpoint", 4);
  await expect(page.getByTestId("settings.models-api-section.http-127-0-0-1-11434")).toBeVisible();
  await reconcileRuntime(page, "set-ollama-endpoint", 5);
  await recordFinalPageState(page, "set-ollama-endpoint");
});

test("open-agent-memory-settings: Open the menu, select Agent, and verify the persistent-instructions editor renders.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "open-agent-memory-settings", 1);
  await expect(page.getByTestId("settings.gates-menu.tab-agent")).toBeVisible();
  await reconcileRuntime(page, "open-agent-memory-settings", 2);
  await page.getByTestId("settings.gates-menu.tab-agent").click();
  await reconcileRuntime(page, "open-agent-memory-settings", 3);
  await expect(page.getByTestId("settings.agent.system-prompt")).toBeVisible();
  await reconcileRuntime(page, "open-agent-memory-settings", 4);
  await recordFinalPageState(page, "open-agent-memory-settings");
});

test("add-an-agent-memory-fact: Type a new fact under Agent, add it, and see a third editable fact appear.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "add-an-agent-memory-fact", 1);
  await page.getByTestId("settings.gates-menu.tab-agent").click();
  await reconcileRuntime(page, "add-an-agent-memory-fact", 2);
  await page.getByTestId("settings.agent.new-fact").fill("The journey catalog is replayed before every release");
  await reconcileRuntime(page, "add-an-agent-memory-fact", 3);
  await page.getByTestId("settings.agent.add").click();
  await reconcileRuntime(page, "add-an-agent-memory-fact", 4);
  await expect(page.getByTestId("settings.agent.fact-edit-2")).toBeVisible();
  await reconcileRuntime(page, "add-an-agent-memory-fact", 5);
  await recordFinalPageState(page, "add-an-agent-memory-fact");
});

test("preview-memory-retrieval: Run the memory preview for a query and keep the results panel reachable.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "preview-memory-retrieval", 1);
  await page.getByTestId("settings.gates-menu.tab-agent").click();
  await reconcileRuntime(page, "preview-memory-retrieval", 2);
  await page.getByTestId("settings.agent.what-should-gates-ai-remember").fill("screenshot tour");
  await reconcileRuntime(page, "preview-memory-retrieval", 3);
  await page.getByTestId("settings.agent.run-preview").click();
  await reconcileRuntime(page, "preview-memory-retrieval", 4);
  await expect(page.getByTestId("settings.agent.rebuild-index")).toBeVisible();
  await reconcileRuntime(page, "preview-memory-retrieval", 5);
  await recordFinalPageState(page, "preview-memory-retrieval");
});

test("first-run-look-around: With nothing configured, the onboarding offers a look around and lands in the composer.", async ({ page }) => {
  await page.goto("/?scenario=first-run#/workspace");
  await expect(page.getByTestId("workspace.editorial-chat.look-around")).toBeVisible();
  await reconcileRuntime(page, "first-run-look-around", 1);
  await page.getByTestId("workspace.editorial-chat.look-around").click();
  await reconcileRuntime(page, "first-run-look-around", 2);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "first-run-look-around", 3);
  await recordFinalPageState(page, "first-run-look-around");
});

test("first-run-connect-openrouter-and-chat: Enter a placeholder key in onboarding, connect, and get the first mocked cloud reply.", async ({
  page,
}) => {
  await page.goto("/?scenario=first-run#/workspace");
  await expect(page.getByTestId("settings.secret-key.input-onboarding-openrouter")).toBeVisible();
  await reconcileRuntime(page, "first-run-connect-openrouter-and-chat", 1);
  await page.getByTestId("settings.secret-key.input-onboarding-openrouter").fill("journey-placeholder-not-a-real-key");
  await reconcileRuntime(page, "first-run-connect-openrouter-and-chat", 2);
  await page.getByTestId("settings.secret-key.connect-onboarding-openrouter").click();
  await reconcileRuntime(page, "first-run-connect-openrouter-and-chat", 3);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible({ timeout: 10000 });
  await reconcileRuntime(page, "first-run-connect-openrouter-and-chat", 4);
  await page.getByTestId("workspace.composer.draft").fill("Hello from the journey.");
  await reconcileRuntime(page, "first-run-connect-openrouter-and-chat", 5);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "first-run-connect-openrouter-and-chat", 6);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "first-run-connect-openrouter-and-chat", 7);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("Your first cloud reply arrived", { timeout: 20000 });
  await reconcileRuntime(page, "first-run-connect-openrouter-and-chat", 8);
  await recordFinalPageState(page, "first-run-connect-openrouter-and-chat");
});

test("whats-new-acknowledge: After an upgrade the panel opens on boot; Got it closes it and the composer is usable.", async ({ page }) => {
  await page.goto("/?scenario=whats-new#/workspace");
  await expect(page.getByTestId("app.whats-new.presentation")).toBeVisible();
  await reconcileRuntime(page, "whats-new-acknowledge", 1);
  await page.getByTestId("app.whats-new.got-it").click();
  await reconcileRuntime(page, "whats-new-acknowledge", 2);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "whats-new-acknowledge", 3);
  await recordFinalPageState(page, "whats-new-acknowledge");
});

test("web-lite-open-workspace: The browser build loads with attachments and deep research disabled, and the composer idle.", async ({
  page,
}) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "web-lite-open-workspace", 1);
  await expect(page.getByTestId("workspace.composer.attach")).toBeDisabled();
  await reconcileRuntime(page, "web-lite-open-workspace", 2);
  await expect(page.getByTestId("workspace.composer-meta.start-deep-research")).toBeDisabled();
  await reconcileRuntime(page, "web-lite-open-workspace", 3);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeDisabled();
  await reconcileRuntime(page, "web-lite-open-workspace", 4);
  await recordFinalPageState(page, "web-lite-open-workspace");
});

test("web-lite-send-message: A cloud turn streams in the browser build exactly as on desktop.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").fill("Hello from Web Lite.");
  await reconcileRuntime(page, "web-lite-send-message", 1);
  await expect(page.getByTestId("workspace.composer-input.composer-send-control")).toBeEnabled();
  await reconcileRuntime(page, "web-lite-send-message", 2);
  await page.getByTestId("workspace.composer-input.composer-send-control").click();
  await reconcileRuntime(page, "web-lite-send-message", 3);
  await expect(page.getByTestId("workspace.editorial-chat.stream")).toContainText("The mocked OpenRouter stream answered this turn", { timeout: 20000 });
  await reconcileRuntime(page, "web-lite-send-message", 4);
  await recordFinalPageState(page, "web-lite-send-message");
});

test("web-lite-open-model-settings: Settings open from the sidebar and the Models tab renders the web-search card.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "web-lite-open-model-settings", 1);
  await expect(page.getByTestId("settings.gates-menu.tab-settings")).toBeVisible();
  await reconcileRuntime(page, "web-lite-open-model-settings", 2);
  await page.getByTestId("settings.gates-menu.tab-models").click();
  await reconcileRuntime(page, "web-lite-open-model-settings", 3);
  await expect(page.getByTestId("settings.models.search-card")).toContainText("Web search");
  await reconcileRuntime(page, "web-lite-open-model-settings", 4);
  await recordFinalPageState(page, "web-lite-open-model-settings");
});

test("web-lite-command-palette: The keyboard shortcut opens the palette in the browser build.", async ({ page }) => {
  await page.goto("/?scenario=desktop-ready#/workspace");
  await page.getByTestId("workspace.composer.draft").click();
  await reconcileRuntime(page, "web-lite-command-palette", 1);
  await page.getByTestId("workspace.composer.draft").press("Control+k");
  await reconcileRuntime(page, "web-lite-command-palette", 2);
  await expect(page.getByTestId("app.command-palette.search-commands-and-threads")).toBeVisible();
  await reconcileRuntime(page, "web-lite-command-palette", 3);
  await expect(page.getByTestId("app.command-palette.row-action:new-conversation")).toBeVisible();
  await reconcileRuntime(page, "web-lite-command-palette", 4);
  await recordFinalPageState(page, "web-lite-command-palette");
});
