// Generated by agent-handles from agent-handles/journey/v1 journeys. Do not edit;
// edit the journey manifest and recompile (npx agent-handles journeys compile).
import { test, expect } from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";

const runtimeObserved = new Map<string, Set<string>>();

async function reconcileRuntime(page: import("@playwright/test").Page, journeyName: string, step: number) {
  await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
  const observation = await page.evaluate(() => {
    const selector = [
      "button", "input", "select", "textarea", "a[href]", "summary",
      "[contenteditable]:not([contenteditable='false'])",
      "[role='button']", "[role='link']", "[role='checkbox']", "[role='radio']",
      "[role='switch']", "[role='tab']", "[role='menuitem']", "[role='option']",
      "[role='combobox']", "[role='textbox']", "[role='slider']", "[role='spinbutton']",
      "[tabindex]:not([tabindex='-1'])",
    ].join(",");
    const visible = (element: Element) => {
      const style = window.getComputedStyle(element);
      const rect = element.getBoundingClientRect();
      return style.display !== "none" && style.visibility !== "hidden" && rect.width > 0 && rect.height > 0;
    };
    const controls = Array.from(document.querySelectorAll(selector)).filter(visible).map((element) => ({
      testId: element.getAttribute("data-testid"),
      tag: element.tagName.toLowerCase(),
      role: element.getAttribute("role"),
      text: (element.textContent ?? "").trim().replace(/\s+/g, " ").slice(0, 120),
    }));
    const allIds = Array.from(document.querySelectorAll("[data-testid]"))
      .filter(visible)
      .map((element) => element.getAttribute("data-testid"))
      .filter((value): value is string => Boolean(value));
    const duplicateTestIds = [...new Set(allIds.filter((value, index) => allIds.indexOf(value) !== index))].sort();
    return {
      url: location.href,
      controls,
      unidentified: controls.filter((control) => !control.testId),
      duplicateTestIds,
    };
  });
  const observed = runtimeObserved.get(journeyName) ?? new Set<string>();
  for (const control of observation.controls) if (control.testId) observed.add(control.testId);
  runtimeObserved.set(journeyName, observed);
  const receipt = {
    schema: "agent-handles/runtime-journey-observation/v1",
    measuredAt: new Date().toISOString(),
    journeyName,
    lastStep: step,
    pageUrl: observation.url,
    observedTestIds: [...observed].sort(),
    unidentified: observation.unidentified,
    duplicateTestIds: observation.duplicateTestIds,
    statement: [...observed].length + " controls observed during this journey; runtime evidence is path-bound, and unvisited states remain uncovered.",
  };
  const directory = path.join(process.cwd(), ".agent-handles", "runtime-observations");
  await fs.mkdir(directory, { recursive: true });
  const file = journeyName.replace(/[^a-z0-9._-]+/gi, "-").replace(/^-+|-+$/g, "") || "journey";
  await fs.writeFile(path.join(directory, file + ".json"), JSON.stringify(receipt, null, 2) + "\n");
  expect(observation.unidentified, "visible interactive controls without data-testid after step " + step).toEqual([]);
  expect(observation.duplicateTestIds, "duplicate visible data-testid values after step " + step).toEqual([]);
}

test("open-settings-and-switch-theme: Reach Settings through the visible sidebar control and select the Light theme.", async ({ page }) => {
  await page.goto("/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "open-settings-and-switch-theme", 1);
  await expect(page.getByTestId("settings.gates-menu.tab-settings")).toBeVisible();
  await reconcileRuntime(page, "open-settings-and-switch-theme", 2);
  await page.getByTestId("settings.segmented.option-theme-light").click();
  await reconcileRuntime(page, "open-settings-and-switch-theme", 3);
  await expect(page.getByTestId("settings.preferences.export-json")).toBeVisible();
  await reconcileRuntime(page, "open-settings-and-switch-theme", 4);
});

test("open-model-provider-settings: Open the menu, select Models, and verify the web-search provider card renders.", async ({ page }) => {
  await page.goto("/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "open-model-provider-settings", 1);
  await expect(page.getByTestId("settings.gates-menu.tab-models")).toBeVisible();
  await reconcileRuntime(page, "open-model-provider-settings", 2);
  await page.getByTestId("settings.gates-menu.tab-models").click();
  await reconcileRuntime(page, "open-model-provider-settings", 3);
  await expect(page.getByTestId("settings.models.search-card")).toContainText("Web search");
  await reconcileRuntime(page, "open-model-provider-settings", 4);
});

test("open-agent-memory-settings: Open the menu, select Agent, and verify the persistent-instructions editor renders.", async ({ page }) => {
  await page.goto("/workspace");
  await page.getByTestId("workspace.sidebar-settings-button.settings-and-menu").click();
  await reconcileRuntime(page, "open-agent-memory-settings", 1);
  await expect(page.getByTestId("settings.gates-menu.tab-agent")).toBeVisible();
  await reconcileRuntime(page, "open-agent-memory-settings", 2);
  await page.getByTestId("settings.gates-menu.tab-agent").click();
  await reconcileRuntime(page, "open-agent-memory-settings", 3);
  await expect(page.getByTestId("settings.agent.you-are-a-thoughtful-collaborator-answer-precisely-prefe")).toBeVisible();
  await reconcileRuntime(page, "open-agent-memory-settings", 4);
});

test("start-a-new-conversation: Use the sidebar control to create a thread and verify the composer is ready.", async ({ page }) => {
  await page.goto("/workspace");
  await page.getByTestId("workspace.editorial-sidebar.begin-a-new-conversation").click();
  await reconcileRuntime(page, "start-a-new-conversation", 1);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "start-a-new-conversation", 2);
});

test("open-workspace-directly: Verify the shareable workspace path loads a usable chat composer without prior navigation.", async ({ page }) => {
  await page.goto("/workspace");
  await reconcileRuntime(page, "open-workspace-directly", 1);
  await expect(page.getByTestId("workspace.composer.draft")).toBeVisible();
  await reconcileRuntime(page, "open-workspace-directly", 2);
});
